services:
  - type: web
    name: genset-monitoring-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind :$PORT --workers 3 src.api_server:app
    healthCheckPath: /health
    envVars:
      - key: DATABASE_PATH
        value: "./data/genset_monitoring.db"
      - key: PORT
        value: "5000"